### ISSUE TITLE
[bug]: duplicated results on intellisense

### ISSUE THREAD

**Issue by icarusgk** [volarjs/volar.js#186] opened 2024-05-25 06:21 UTC
# Description

When typing the name of a variable in `<script>`, an attribute or event handler in `<template>` or a selector in `<style>` the suggestions provided by Intellisense are duplicated.

I haven't noticed this issue in VS Code yet, but I have encountered it in the SFC Playground, Zed Editor, IDX Editor, and GitHub Codespaces.

Example:

![Example](https://github.com/volarjs/volar.js/assets/38413630/4e1ed390-f015-4693-a20d-27bb83ceaa65)

## Workarounds

Refresh the SFC Playground with the already written code inside and the problem goes away.

**Comment by icarusgk** [comment] 2024-08-21 23:44
**Update:** Zed has [pinned](https://github.com/zed-industries/zed/pull/9846) `@vuejs/language-server` to version `1.8` due to this issue. https://zed.dev/docs/languages/vue

**Comment by johnsoncodehk** [comment] 2024-09-08 01:38
Fixed by https://github.com/vuejs/repl/commit/f9f650ada945f7ea597b7e7b51c132c4594bd5cb

**Closed by johnsoncodehk** 2024-09-08 01:38 UTC
Labels: bug

**Comment by icarusgk** [comment] 2024-09-08 23:26
Thank you! 😄

**Comment by Meesayen** [comment] 2024-11-13 09:50
Hi @johnsoncodehk  I'm now experiencing this in VS Code, with latest versions of the extension, the vue-tsc dependency and typescript. If I disable the extension and re-enable it, the issue disappears, but as soon as you restart the whole extension host of VS Code, the issue is there again.
