### ISSUE TITLE
@volar/monaco: add @types/xxx automaticlly

### ISSUE THREAD

**Issue by zh-lx** [volarjs/volar.js#63] opened 2023-09-07 11:51 UTC
When using `@volar/monaco`, for third-party libraries that don't have types in `package.json`(such as `react`), can `@types/xxx` be automatically added to obtain type prompts. 

For example, when I import 'react' and it doesn't hava `types` field in `package.json`, I hope `@volar/monaco` can add `@types/react` automaticly.

<img width="730" alt="image" src="https://github.com/volarjs/volar.js/assets/73059627/39a37cb8-1b14-4f57-9597-da115b6049e1">

**Comment by johnsoncodehk** [comment] 2024-07-01 18:51
Duplicate of #81

**Closed by johnsoncodehk** 2024-07-01 18:51 UTC
